server_url: http://localhost:8080
realm: auth-system
admin_user: admin
admin_password: admin

groups:
  - name: viewer
    subgroups:
      - name: operational__viewer
      - name: technical__viewer
      - name: debrifing__viewer
  - name: operator
    subgroups:
      - name: operational__operator
      - name: technical__operator
      - name: debrifing__operator
      - name: training__operator
  - name: technician
    subgroups:
      - name: technical__technician
  - name: instructor
    subgroups:
      - name: training_plan__instructor
  - name: administrator
    subgroups:
      - name: operational__administrator
      - name: technical__administrator
      - name: debrifing__administrator
      - name: training_plan__administrator
      - name: training__administrator
  - name: superusers
    subgroups:
      - name: administrator
      - name: instructor
      - name: technician
      - name: operator
      - name: viewer
      
users:
  - username: superuser
    email: superuser@aeronous.com
    password: 123456
    firstName: superuser
    lastName: superuser
    group: superusers
    client_roles:
      realm-management:
        - realm-admin
  - username: viewer__user
    email: vieweruser@aeronous.com
    password: 123456
    firstName: viewer
    lastName: viewer
    group: viewer
  - username: operator__user
    email: operatoruser@aeronous.com
    password: 123456
    firstName: operator
    lastName: operator
    group: operator
  - username: technician__user
    email: technicianuser@aeronous.com
    password: 123456
    firstName: technician
    lastName: technician
    group: technician
  - username: instructor__user
    email: instructoruser@aeronous.com
    password: 123456
    firstName: instructor
    lastName: instructor
    group: instructor
  - username: administrator__user
    email: administratoruser@aeronous.com
    password: 123456
    firstName: administrator
    lastName: administrator
    group: administrator

clients:
  - client_id: be-c4i
    publicClient: false
    secret: true
    serviceAccountsEnabled: true
    redirect_uris:
      - "http://localhost:3000/*"
    web_origins:
      - "http://localhost:3000"

  - client_id: fe-login
    publicClient: false
    secret: false
    serviceAccountsEnabled: true
    redirect_uris:
      - "http://localhost:4200/*"
    web_origins:
      - "http://localhost:4200"
